/*
 *  This JavaScript file for Rich Text Editor
 *  this component works for GnimJS
 *  Version 0.1.0
 *  Write by Ming
 *  Date 2011.10.16
 */
(function(D,g,s){function t(a,b){var c=this,d=g(a);if(1!=d.length)d.each(function(a){new t(a,b)});else{var f=c.autoid=++H;t[f]=c;c.xhtml=!1!==b.xhtml;c._mode=!0;var e=c.$d=k("div",p).attr("autoid",f).insertAfter(d),r=c.$b=k("div",u).appendTo(e),h=0;g(E).each(function(a){a?function(a,d){if(1==a[q]||3==a[q]){var e;g.isArray(a[w])?I(c,a[l],b[a[l]]||a[w],a[F]).appendTo(r):e="c"===a[w]?k("button",x).click(function(b){y(b);J(b.srcElement||b.currentTarget,function(b){c[a[l]](b)})}).appendTo(r):k("button",
x).click(function(b){y(b);c[a[l]]()}).appendTo(r);e&&(e.attr("title",a[F]).css(z(d)).hover(function(){e.css(z(d,1)).addClass(G)},function(){e.css(z(d)).removeClass(G)}),h++)}}(a,h):0===a?r.append(k("span",K)):r.append("<br />")});c.$t=d.css(m).addClass(L).appendTo(e);var f=M+f,n=c.$i=k("iframe",N).attr("id",f).appendTo(e);c.$m=k("div",O).css(m).css({opacity:.1}).appendTo(e);e=c.d=(c.i=n[0].contentWindow||D.frames[f]).document;e.open();e.write(b.html||P(b.charset,b.cssFile,b.content||d[0].value));
e.close();e.designMode="on";if(b[v]!==s)c[v](b[v]);f=function(){c._update()};g(e).keyup(f).mouseup(f);e=function(){c._update(1)};d.keyup(e).mouseup(e)}}function y(a){g.noBubble(a);g.noDefault(a)}function k(a,b){return g("<"+a+"></"+a+">").addClass(b)}function I(a,b,c,d){var f=k("select",Q);f[0].options.add(new Option(d));for(d=0;d<c.length;d++){var e=c[d];f[0].options.add(g.isArray(e)?new Option(e[0],e[1]):new Option(e,e))}return f.change(function(c){c=c.srcElement||c.currentTarget;0!=c.selectedIndex&&
(a[b](c.value),c.selectedIndex=0)})}function J(a,b){if(!h){h=k("div",A).appendTo("body");for(var c=0;3>=c;c++)for(var d=k("div",R).appendTo(h),f=85*c,e=0;3>=e;e++)for(var l=85*e,m=0;3>=m;m++)(function(a){k("button",S).css({backgroundColor:a}).click(function(b){y(b);h.cb&&h.cb(a)}).appendTo(d)})("#"+g.toHex(256*(256*f+l)+85*m,6))}h.cb=b;h.css(T(a)).css(n)}function T(a){for(var b=0,c=a.offsetHeight;a.offsetParent;)b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;return{left:b+"px",top:c+"px"}}function P(a,
b,c){var d;d="<!DOCTYPE html><html><head>";d+='<meta http-equiv="Content-Type" content="text/html; charset='+(a||"UTF-8")+'" />';d+="<title>RichEditor</title>";d+="<style>::selection{background:#000;color:#fff;}::-moz-selection{background:#000;color:#fff;}</style>";b&&(d+='<link rel="stylesheet" type="text/css" href="'+b+'">');return d+="</head><body>"+(c||"")+"</body></html>"}function z(a,b){return{backgroundPosition:(b?"-30px ":"0 ")+30*-a+"px"}}var H=0,h=null,B=g.broswer.msie,U=B&&6==g.broswer.version,
M="richeditor_",p="richeditor",A=p+"-color",R=A+"-line",S=A+"-item",u=p+"-toolbox",Q=u+"-select",K=u+"-divider",x=u+"-item",G=x+"-hover",L=p+"-textarea",N=p+"-iframe",O=p+"-mask",n={display:"block"},m={display:"none"},q=0,l=1,F=2,w=4,v="styleWithCSS",E=[[1,"undo","\u64a4\u6d88"],[1,"redo","\u91cd\u505a"],0,[3,"print","\u6253\u5370"],0,[1,"justifyleft","\u5de6\u5bf9\u9f50"],[1,"justifycenter","\u5c45\u4e2d"],[1,"justifyright","\u53f3\u5bf9\u9f50"],[1,"justifyfull","\u4e24\u7aef\u5bf9\u9f50"],0,[1,
"createlink","\u94fe\u63a5","\u8f93\u5165\u94fe\u63a5\u5730\u5740\uff1a"],[1,"unlink","\u53d6\u6d88\u94fe\u63a5"],[1,"insertimage","\u56fe\u7247","\u8f93\u5165\u56fe\u7247\u5730\u5740\uff1a"],[1,"inserthorizontalrule","\u5206\u5272\u7ebf"],0,[1,"insertunorderedlist","\u65e0\u5e8f\u5217\u8868"],[1,"insertorderedlist","\u6709\u5e8f\u5217\u8868"],0,[1,"indent","\u5de6\u7f29\u8fdb"],[1,"outdent","\u53f3\u7f29\u8fdb"],0,[1,"removeformat","\u5220\u9664\u6837\u5f0f"],!1,[1,"formatblock","\u6807\u9898","\u6807\u9898:",
[["\u4e00\u7ea7\u6807\u9898","<h1>"],["\u4e8c\u7ea7\u6807\u9898","<h2>"],["\u4e09\u7ea7\u6807\u9898","<h3>"],["\u56db\u7ea7\u6807\u9898","<h4>"],["\u4e94\u7ea7\u6807\u9898","<h5>"],["\u516d\u7ea7\u6807\u9898","<h6>"],["\u683c\u5f0f\u5316","<pre>"],["\u6bb5\u843d","<p>"]]],[1,"fontname","\u5b57\u4f53","\u5b57\u4f53:",["Verdana","Arial","Georgia"]],[1,"fontsize","\u5b57\u53f7","\u5b57\u53f7:",[1,2,3,4,5,6,7]],0,[1,"forecolor","\u5b57\u4f53\u989c\u8272","\u5b57\u4f53\u989c\u8272:","c"],[1,B?"backcolor":
"hilitecolor","\u5b57\u4f53\u80cc\u666f","\u80cc\u666f\u989c\u8272:","c"],0,[1,"bold","\u52a0\u7c97"],[1,"italic","\u659c\u4f53"],[1,"underline","\u4e0b\u5212\u7ebf"],[1,"strikethrough","\u5220\u9664\u7ebf"],0,[1,"subscript","\u4e0b\u6807"],[1,"superscript","\u4e0a\u6807"],[2,"selectall"],[2,v],[4,"focus"]],C={mode:function(a){if(a===s)return this._mode;this._mode=!!a;this.$t.css(a?m:n);this.$i.css(a?n:m);this.$b.css(a?n:m)},html:function(a){var b=g(this.d).find("body").html(a);a===s&&this.xhtml&&
(b=b.replace(/<span class="apple-style-span">(.*)<\/span>/gi,"$1").replace(/ class="apple-style-span"/gi,"").replace(/<span style="">/gi,"").replace(/<br>/gi,"<br />").replace(/<br ?\/?>$/gi,"").replace(/^<br ?\/?>/gi,"").replace(/(<img [^>]+[^\/])>/gi,"$1 />").replace(/<b\b[^>]*>(.*?)<\/b[^>]*>/gi,"<strong>$1</strong>").replace(/<i\b[^>]*>(.*?)<\/i[^>]*>/gi,"<em>$1</em>").replace(/<u\b[^>]*>(.*?)<\/u[^>]*>/gi,'<span style="text-decoration:underline">$1</span>').replace(/<(b|strong|em|i|u) style="font-weight: normal;?">(.*)<\/(b|strong|em|i|u)>/gi,
"$2").replace(/<(b|strong|em|i|u) style="(.*)">(.*)<\/(b|strong|em|i|u)>/gi,'<span style="$2"><$4>$3</$4></span>').replace(/<span style="font-weight: normal;?">(.*)<\/span>/gi,"$1").replace(/<span style="font-weight: bold;?">(.*)<\/span>/gi,"<strong>$1</strong>").replace(/<span style="font-style: italic;?">(.*)<\/span>/gi,"<em>$1</em>").replace(/<span style="font-weight: bold;?">(.*)<\/span>|<b\b[^>]*>(.*?)<\/b[^>]*>/gi,"<strong>$1</strong>"));return b},enable:function(a){this.$m.css(!U&&a?m:n);B||
(this.d.designMode=a?"on":"off")},_cmd:function(a,b){this.focus().d.execCommand(a,!1,b);return this._update()},_update:function(a){var b=this.$t[0];a?this.html(b.value):b.value=this.html();return this}};g(E).each(function(a){if(a){if(1==a[q]||2==a[q]){var b;b=a[3]===s?new Function("this._cmd('"+a[l]+"');"):new Function("v",'if(typeof v=="undefined"){v=prompt("'+(a[3]||TEXT_NEED_VAL)+'","");}if(v){this._cmd(\''+a[l]+"',v);}");C[a[l]]=b}if(3==a[q]||4==a[q])C[a[l]]=new Function("this.i."+a[l]+"();return this;")}});
t.prototype=C;g("body").click(function(){h&&h.css(m)});D.RichEditor=t})(window,Gnim);

