/*
 *  This JavaScript file for Rich Text Editor
 *  this component works for GnimJS
 *  Version 0.1.0
 *  Write by Ming
 *  Date 2011.10.16
 */
(function(A,f,p){function q(a,b){var c=this,g=f(a);if(1!=g.length)g.each(function(a){new q(a,b)});else{var e=c.autoid=++E;q[e]=c;c.xhtml=!1!==b.xhtml;c._mode=!0;var d=c.$d=i("div",m).attr("autoid",e).insertAfter(g),o=c.$b=i("div",r).appendTo(d),h=0;f(B).each(function(a){a?function(a,d){if(1==a[n]||3==a[n]){var e;f.isArray(a[t])?F(c,a[j],b[a[j]]||a[t],a[C]).appendTo(o):e="c"===a[t]?i("button",u).click(function(b){v(b);G(b.srcElement||b.currentTarget,function(b){c[a[j]](b)})}).appendTo(o):i("button",
u).click(function(b){v(b);c[a[j]]()}).appendTo(o);e&&(e.attr("title",a[C]).css(w(d)).hover(function(){e.css(w(d,1)).addClass(D)},function(){e.css(w(d)).removeClass(D)}),h++)}}(a,h):0===a?o.append(i("span",H)):o.append("<br />")});c.$t=g.css(k).addClass(I).appendTo(d);var e=J+e,l=c.$i=i("iframe",K).attr("id",e).appendTo(d);c.$m=i("div",L).css(k).css({opacity:0.1}).appendTo(d);d=c.d=(c.i=A.frames[e]||l[0].contentWindow).document;d.open();d.write(b.html||M(b.charset,b.cssFile,b.content||g[0].value));
d.close();d.designMode="on";if(b[s]!==p)c[s](b[s]);e=function(){c._update()};f(d).keyup(e).mouseup(e);d=function(){c._update(1)};g.keyup(d).mouseup(d)}}function v(a){f.noBubble(a);f.noDefault(a)}function i(a,b){return f("<"+a+"></"+a+">").addClass(b)}function F(a,b,c,g){var e=i("select",N);e[0].options.add(new Option(g));for(g=0;g<c.length;g++){var d=c[g];e[0].options.add(f.isArray(d)?new Option(d[0],d[1]):new Option(d,d))}return e.change(function(c){c=c.srcElement||c.currentTarget;0!=c.selectedIndex&&
(a[b](c.value),c.selectedIndex=0)})}function G(a,b){if(!h){h=i("div",x).appendTo("body");for(var c=0;3>=c;c++)for(var g=i("div",O).appendTo(h),e=85*c,d=0;3>=d;d++)for(var j=85*d,k=0;3>=k;k++)(function(a){i("button",P).css({backgroundColor:a}).click(function(b){v(b);h.cb&&h.cb(a)}).appendTo(g)})("#"+f.toHex(256*(256*e+j)+85*k,6))}h.cb=b;h.css(Q(a)).css(l)}function Q(a){for(var b=0,c=a.offsetHeight;a.offsetParent;)b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;return{left:b+"px",top:c+"px"}}function M(a,
b,c){a="<!DOCTYPE html><html><head>"+('<meta http-equiv="Content-Type" content="text/html; charset='+(a||"UTF-8")+'" />')+"<title>RichEditor</title><style>::selection{background:#000;color:#fff;}::-moz-selection{background:#000;color:#fff;}</style>";b&&(a+='<link rel="stylesheet" type="text/css" href="'+b+'">');return a+("</head><body>"+(c||"")+"</body></html>")}function w(a,b){return{backgroundPosition:(b?"-30px ":"0 ")+30*-a+"px"}}var E=0,h=null,y=f.broswer.msie,R=y&&6==f.broswer.version,J="richeditor_",
m="richeditor",x=m+"-color",O=x+"-line",P=x+"-item",r=m+"-toolbox",N=r+"-select",H=r+"-divider",u=r+"-item",D=u+"-hover",I=m+"-textarea",K=m+"-iframe",L=m+"-mask",l={display:"block"},k={display:"none"},n=0,j=1,C=2,t=4,s="styleWithCSS",B=[[1,"undo","\u64a4\u6d88"],[1,"redo","\u91cd\u505a"],0,[3,"print","\u6253\u5370"],0,[1,"justifyleft","\u5de6\u5bf9\u9f50"],[1,"justifycenter","\u5c45\u4e2d"],[1,"justifyright","\u53f3\u5bf9\u9f50"],[1,"justifyfull","\u4e24\u7aef\u5bf9\u9f50"],0,[1,"createlink","\u94fe\u63a5",
"\u8f93\u5165\u94fe\u63a5\u5730\u5740\uff1a"],[1,"unlink","\u53d6\u6d88\u94fe\u63a5"],[1,"insertimage","\u56fe\u7247","\u8f93\u5165\u56fe\u7247\u5730\u5740\uff1a"],[1,"inserthorizontalrule","\u5206\u5272\u7ebf"],0,[1,"insertunorderedlist","\u65e0\u5e8f\u5217\u8868"],[1,"insertorderedlist","\u6709\u5e8f\u5217\u8868"],0,[1,"indent","\u5de6\u7f29\u8fdb"],[1,"outdent","\u53f3\u7f29\u8fdb"],0,[1,"removeformat","\u5220\u9664\u6837\u5f0f"],!1,[1,"formatblock","\u6807\u9898","\u6807\u9898:",[["\u4e00\u7ea7\u6807\u9898",
"<h1>"],["\u4e8c\u7ea7\u6807\u9898","<h2>"],["\u4e09\u7ea7\u6807\u9898","<h3>"],["\u56db\u7ea7\u6807\u9898","<h4>"],["\u4e94\u7ea7\u6807\u9898","<h5>"],["\u516d\u7ea7\u6807\u9898","<h6>"],["\u683c\u5f0f\u5316","<pre>"],["\u6bb5\u843d","<p>"]]],[1,"fontname","\u5b57\u4f53","\u5b57\u4f53:",["Verdana","Arial","Georgia"]],[1,"fontsize","\u5b57\u53f7","\u5b57\u53f7:",[1,2,3,4,5,6,7]],0,[1,"forecolor","\u5b57\u4f53\u989c\u8272","\u5b57\u4f53\u989c\u8272:","c"],[1,y?"backcolor":"hilitecolor","\u5b57\u4f53\u80cc\u666f",
"\u80cc\u666f\u989c\u8272:","c"],0,[1,"bold","\u52a0\u7c97"],[1,"italic","\u659c\u4f53"],[1,"underline","\u4e0b\u5212\u7ebf"],[1,"strikethrough","\u5220\u9664\u7ebf"],0,[1,"subscript","\u4e0b\u6807"],[1,"superscript","\u4e0a\u6807"],[2,"selectall"],[2,s],[4,"focus"]],z={mode:function(a){if(a===p)return this._mode;this._mode=!!a;this.$t.css(a?k:l);this.$i.css(a?l:k);this.$b.css(a?l:k)},html:function(a){var b=f(this.d).find("body").html(a);a===p&&this.xhtml&&(b=b.replace(/<span class="apple-style-span">(.*)<\/span>/gi,
"$1").replace(/ class="apple-style-span"/gi,"").replace(/<span style="">/gi,"").replace(/<br>/gi,"<br />").replace(/<br ?\/?>$/gi,"").replace(/^<br ?\/?>/gi,"").replace(/(<img [^>]+[^\/])>/gi,"$1 />").replace(/<b\b[^>]*>(.*?)<\/b[^>]*>/gi,"<strong>$1</strong>").replace(/<i\b[^>]*>(.*?)<\/i[^>]*>/gi,"<em>$1</em>").replace(/<u\b[^>]*>(.*?)<\/u[^>]*>/gi,'<span style="text-decoration:underline">$1</span>').replace(/<(b|strong|em|i|u) style="font-weight: normal;?">(.*)<\/(b|strong|em|i|u)>/gi,"$2").replace(/<(b|strong|em|i|u) style="(.*)">(.*)<\/(b|strong|em|i|u)>/gi,
'<span style="$2"><$4>$3</$4></span>').replace(/<span style="font-weight: normal;?">(.*)<\/span>/gi,"$1").replace(/<span style="font-weight: bold;?">(.*)<\/span>/gi,"<strong>$1</strong>").replace(/<span style="font-style: italic;?">(.*)<\/span>/gi,"<em>$1</em>").replace(/<span style="font-weight: bold;?">(.*)<\/span>|<b\b[^>]*>(.*?)<\/b[^>]*>/gi,"<strong>$1</strong>"));return b},enable:function(a){this.$m.css(!R&&a?k:l);y||(this.d.designMode=a?"on":"off")},_cmd:function(a,b){this.focus().d.execCommand(a,
!1,b);return this._update()},_update:function(a){var b=this.$t[0];a?this.html(b.value):b.value=this.html();return this}};f(B).each(function(a){if(a){if(1==a[n]||2==a[n]){var b;b=a[3]===p?new Function("this._cmd('"+a[j]+"');"):new Function("v",'if(typeof v=="undefined"){v=prompt("'+(a[3]||TEXT_NEED_VAL)+'","");}if(v){this._cmd(\''+a[j]+"',v);}");z[a[j]]=b}if(3==a[n]||4==a[n])z[a[j]]=new Function("this.i."+a[j]+"();return this;")}});q.prototype=z;f("body").click(function(){h&&h.css(k)});A.RichEditor=
q})(window,Gnim);
